id = "zed.extension.template"
name = "zed.extension.template"
description = "Zed extension template"
version = "0.0.1"
schema_version = 1
authors = ["Elone Hoo <hi@elonehoo.me>"]
repository = "https://github.com/elonehoo/zed.extension.template"
